// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8gaAX3qt6wfWBjok-7em8cDZx5zg6kQw',
    appId: '1:785303566499:web:b5180786eda4889c656716',
    messagingSenderId: '785303566499',
    projectId: 'inkstreak-89ad9',
    authDomain: 'inkstreak-89ad9.firebaseapp.com',
    storageBucket: 'inkstreak-89ad9.firebasestorage.app',
    measurementId: 'G-LRW0S22JBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcEPgp2pbnZUJfxWaidzmHTEI-WpWcvak',
    appId: '1:785303566499:android:614a1514afdaf686656716',
    messagingSenderId: '785303566499',
    projectId: 'inkstreak-89ad9',
    storageBucket: 'inkstreak-89ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpZGPuvRq6ARwpeF8kL96JDGZWAwrdJZY',
    appId: '1:785303566499:ios:eeb1fa093bb651b0656716',
    messagingSenderId: '785303566499',
    projectId: 'inkstreak-89ad9',
    storageBucket: 'inkstreak-89ad9.firebasestorage.app',
    iosClientId: '785303566499-5hfagragoiujb9kf79nop3dfgcvqhn80.apps.googleusercontent.com',
    iosBundleId: 'tech.watsoup.inkstreak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpZGPuvRq6ARwpeF8kL96JDGZWAwrdJZY',
    appId: '1:785303566499:ios:3851eb006210c3c9656716',
    messagingSenderId: '785303566499',
    projectId: 'inkstreak-89ad9',
    storageBucket: 'inkstreak-89ad9.firebasestorage.app',
    iosClientId: '785303566499-1rl8hnk841enkpegb0e4e151u5kk65ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.inkstreak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8gaAX3qt6wfWBjok-7em8cDZx5zg6kQw',
    appId: '1:785303566499:web:50be650663de0c0e656716',
    messagingSenderId: '785303566499',
    projectId: 'inkstreak-89ad9',
    authDomain: 'inkstreak-89ad9.firebaseapp.com',
    storageBucket: 'inkstreak-89ad9.firebasestorage.app',
    measurementId: 'G-VPJS28VLMS',
  );

}